sudo: required
dist: trusty

rvm: 2.2

services:
  - docker

cache: bundler

services:
  - docker

env:
  global:
    - KITCHEN_DRIVER=docker
    - KITCHEN_PROVIDER=docker
    - KITCHEN_PLATFORM=ubuntu-14.04
  matrix:
    - ANSIBLE_VERSION=latest

install:
  - bundle install --path vendor/bundle

before_script:
  - sudo iptables -L DOCKER || sudo iptables -N DOCKER

script:
  - bundle exec kitchen test
