---
- name: Assume that the requested Packer version is not installed until we check
  set_fact:
    packer_version_already_installed: False

- name: Check Packer version
  shell: packer --version
  register: packer_current_version
  ignore_errors: True

- name: Check if we need to install the requested version
  set_fact:
    packer_version_already_installed: "{{ packer_current_version.stdout | search(packer_version)) }}"
  when: packer_current_version | success

- name: Show version info for debugging
  debug:
    msg: "Version requested is {{ packer_version }}, found {{ packer_current_version.stdout }}, install needed is {{ not packer_version_already_installed }}"
