---
- name: create packer directories
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - "{{ packer_archive_path }}"
    - "{{ packer_binary_path }}"

- name: fetch packer
  get_url:
    url: "{{ packer_download_url }}"
    dest: "{{ packer_archive_path }}"

- name: link packer-packer as packer if it does not exist
  file:
    state: absent
    path: "{{ packer_binary_path }}/packer-packer"

- name: remove old packer version
  shell: "rm -f {{ packer_binary_path }}/packer*"

- name: unpack packer
  unarchive:
    src: "{{ packer_archive_path }}/{{ packer_download_url }}"
    dest: "{{ packer_binary_path }}"
    copy: False

- name: fetch packer plugins
  get_url:
    url: "{{ item.value.url }}"
    dest: "{{ packer_binary_path }}/{{ item.key }}"
    force: "{{ packer_plugins_force_install }}"
  with_dict: packer_plugins

- name: make packer binaries executable
  shell: "chmod 0755 {{ packer_binary_path }}/packer*"

- name: link packer-packer as packer
  file:
    state: link
    src: "{{ packer_binary_path }}/packer-packer"
    dest: "{{ packer_binary_path }}/packer"
    owner: root
    group: root
