---
- name: create packer directories
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - "{{ packer_archive_path }}"
    - "{{ packer_binary_path }}"

- name: fetch packer
  get_url:
    url: "{{ packer_download_url }}"
    dest: "{{ packer_archive_path }}"

- name: remove old packer binaries
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob: "{{ packer_binary_path }}/packer*"

- name: unpack packer
  unarchive:
    src: "{{ packer_archive_path }}/{{ packer_download_url | basename }}"
    dest: "{{ packer_binary_path }}"
    copy: False

- name: install packer plugins
  get_url:
    url: "{{ item.value.url }}"
    dest: "{{ packer_binary_path }}/{{ item.key }}"
    force: "{{ packer_plugins_force_install }}"
  with_dict: packer_plugins

- name: make packer binaries executable
  file:
    path: "{{ item }}"
    state: file
    mode: 0755
  with_fileglob: "{{ packer_binary_path }}/packer*"
