---
- name: Install Debian packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: True
  with_items:
    - unzip
  when: ansible_os_family | match("Debian")

- name: Install Red Hat packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip
  when: ansible_os_family | match("RedHat")
